#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"

if docker inspect deluged >/dev/null 2>&1; then docker rm -f deluged; fi
if docker inspect deluged-proxy >/dev/null 2>&1; then docker rm -f deluged-proxy; fi
if docker network inspect deluge >/dev/null 2>&1; then docker network rm deluge; fi
